### PR TITLE
Add convenience methods & types for sending error & purchase preset signals

### PR DESCRIPTION
**Pull request by Jeehut**
This should be merged together with https://github.com/TelemetryDeck/docs/pull/82.

### CODE REVIEW

**Comment by Jeehut** [comment]
@winsmith This should be merge-ready now. Please note that this targets the grand-rename branch. You might want to merge #153 first, then edit the target branch to `main` and merge.

**Review by winsmith — APPROVED** [review]
Great work, and well-documented! Go!

**Comment by mattcorey** [comment]
Any schedule for when this will be merged? 🙏

**Comment by Jeehut** [comment]
@mattcorey Merging and releasing now (has a busy family weekend). 🎉

**Pull request merged**
