### PR TITLE
Add full data-race safety and enable strict concurrency checking for Swift 6 compatibility

### PR DESCRIPTION
**Pull request by Jeehut**
Implements #165.

Note that this is based off of the branch of #173 and therefore supersedes it. If this is merged first, #173 can be closed.

You might want to also check out my article in https://github.com/TelemetryDeck/docs/pull/98 to understand the changes better.

Also, it's probably a good idea if a few real-world customers give these changes a spin, either by including the `feature/data-race-safety` branch or on the `main` branch once this is merged. We should have some real-world testing before making a regular release.

### CODE REVIEW

**Comment by Jeehut** [comment]
@winsmith I fixed the CI immediately after receiving the notification that CI failed. All passing now.

**Comment by Jeehut** [comment]
@winsmith Please don't merge just yet, I just tested this branch in a real-world project and ran into this issue:

Bildschirmfoto 2024-08-01 um 16 01 50

Let me take another look tomorrow, it seems marking `TelemetryManager` as `@unchecked Sendable` wasn't quite right.

**Comment by Jeehut** [comment]
@winsmith I played around a lot to fix this issue, the only thing that worked were the changes I committed in 483b686d8f3ccbdee61e97716a1c722e24754164. In my testing with iOS & macOS targets, it worked as expected.

But I just want to reiterate that it's probably a good idea if a few customers first try this out before we make an official release. For me, it worked, but maybe you wanna ask one or two customers if they wanna give it a try with the `main` branch after this is merged. Or we could also make `2.4.0-beta.1` release. Maybe you wanna ask the customers who reported #172?

**Comment by winsmith** [comment]
Fantastic work. I'll find a few customers to test this with!

**Comment by winsmith** [comment]
Let's merge this into main, but let's not add a release just yet. Then we can publish the blog post and we can hit up a few select customers. Would that work for you?

**Comment by Jeehut** [comment]
@winsmith Yeah, sounds good. Let's go, I'm merging. 🎉

**Pull request merged**
